# Generated by Django 4.1.3 on 2022-11-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relatives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relative',
            old_name='name',
            new_name='first_name',
        ),
    ]
